kind: Deployment
apiVersion: apps/v1
metadata:
  name: go-banano-utils-deployment
  namespace: banano-utils
  labels:
    app: go-banano-utils
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-banano-utils
  template:
    metadata:
      labels:
        app: go-banano-utils
    spec:
      containers:
        - name: go-banano-utils
          image: replaceme
          resources:
            requests:
              cpu: 50m
              memory: 25Mi
            limits:
              cpu: 200m
              memory: 50Mi
          ports:
            - containerPort: 3000
          imagePullPolicy: 'Always'
          env:
            - name: MEDIUM_SECRET
              valueFrom:
                secretKeyRef:
                  name: banano-utils-secrets
                  key: MEDIUM_SECRET
            - name: MEDIUM_USER_ID
              valueFrom:
                secretKeyRef:
                  name: banano-utils-secrets
                  key: MEDIUM_USER_ID
      imagePullSecrets:
        - name: regcred
