kind: Deployment
apiVersion: apps/v1
metadata:
  name: banano-utils-deployment
  namespace: banano-utils
  labels:
    app: banano-utils
spec:
  replicas: 2
  selector:
    matchLabels:
      app: banano-utils
  template:
    metadata:
      labels:
        app: banano-utils
    spec:
      containers:
        - name: banano-utils
          image: replaceme
          command: ["/bin/bash", "-c"]
          resources:
            requests:
              cpu: 200m
              memory: 100Mi
            limits:
              cpu: 400m
              memory: 200Mi
          args: ["./banano-utils"]
          ports:
            - containerPort: 3000
          imagePullPolicy: "Always"
      imagePullSecrets:
        - name: regcred
